name: Orlen Website Bot 

on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    # <--- Zmiana na v4

      - name: Set up Python
        uses: actions/setup-python@v5 # <--- Zmiana na v5
        with:
          python-version: '3.11'      # <--- Zmiana na 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run Scrapers and Logic
        env:
          GEMINI_API_KEY_1: ${{ secrets.GEMINI_API_KEY_1 }}
          GEMINI_API_KEY_2: ${{ secrets.GEMINI_API_KEY_2 }}
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
          USER_KEY: ${{ secrets.USER_KEY }}
        run: |
          # Kolejność uruchamiania skryptów
          scrapy crawl hurtowe_orlen
          scrapy crawl bankier_orlen
          scrapy crawl pap_orlen
          scrapy crawl tvn24_orlen
          scrapy crawl cena_max_mp
          python kalkulator_detaliczny.py
          python czyszczenie_danych.py
          python ocena_ai.py
          python buduj_tabele.py
          python trenuj_model.py


      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "Automatyczna aktualizacja danych i prognoz: $(date)" || echo "Brak zmian do zapisu"
          git push
